# 使い方
# docker-compose up --build -d
# mysql --help | grep my.cnf

version: '3.8'
 
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/
  php-fpm:
    build: ./php-fpm
    restart: always
    volumes:
      - ./src:/var/www/
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : pass
      MYSQL_DATABASE : blogApp
      MYSQL_USER : user
      MYSQL_PASSWORD : pass
    ports:
      - 3306:3306
    volumes:
    - data:/var/lib/mysql 
    - ./mysql/my.cnf:/etc/mysql/my.cnf
volumes:
    data: